[module]
      [[module.mounts]]
      source = "content"
      target = "content"
      [[module.mounts]]
      source = "static"
      target = "static"
      [[module.mounts]]
      source = "layouts"
      target = "layouts"
      [[module.mounts]]
      source = "data"
      target = "data"
      [[module.mounts]]
      source = "assets"
      target = "assets"
      [[module.mounts]]
      source = "i18n"
      target = "i18n"
      [[module.mounts]]
      source = "archetypes"
      target = "archetypes"
    [[module.mounts]]
        # Workaround for https://github.com/gohugoio/hugo/issues/6945
        source = "assets/scss/_vendor/bootstrap/_vendor"
        target = "assets/scss/_vendor/bootstrap/vendor"
    [[module.imports]]
        path="github.com/twbs/bootstrap"
        [[module.imports.mounts]]
            source = "scss"
            target = "assets/scss/_vendor/bootstrap"
        [[module.imports.mounts]]
            source = "dist/js"
            target = "assets/js/_vendor/bootstrap"